server:
  port: 18090
  servlet:
    context-path: /muter

spring:
  datasource:
    url: jdbc:postgresql://192.168.2.64:5432/muter #pc local
#    url: jdbc:postgresql://localhost:5432/muter #aws local
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
mail:
  domain: naver.com
  host: smtp.naver.com
  port: 465
  username: talkative-muter
  password: Muter!23
  transport:
    protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true
    ssl:
      enable: true
  debug:
    true

logging.level:
  org.hibernate.SQL: debug