server:
  port: 18090
  servlet:
    context-path: /muter

spring:
  datasource:
    url: jdbc:postgresql://192.168.2.64:5432/muter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

logging.level:
  org.hibernate.SQL: debug