server:
  port: 18090
  servlet:
    context-path: /muter

spring:
  datasource:
    url: jdbc:postgresql://192.168.2.64:5432/muter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  mail:
    host: smtp.gmail.com
    port: 567
    username: bangseek87
    password: Muter12#$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging.level:
  org.hibernate.SQL: debug